//
//  SignUpPresenter.swift
//  Udecide
//
//  Created by hb on 11/04/19.
//  Copyright (c) 2019 hb. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SignUpPresentationLogic {
    func presentUniqeUser(response: CheckUniqueUSer.ViewModel?,  message: String, success: String)
}

class SignUpPresenter: SignUpPresentationLogic {
    weak var viewController: SignUpDisplayLogic?
    
    func presentUniqeUser(response: CheckUniqueUSer.ViewModel?,  message: String, success: String) {
        self.viewController?.didReceiveUniqeUser(response: response, message: message, success: success)
    }
}
