//
//  SignUpInteractor.swift
//  Udecide
//
//  Created by hb on 11/04/19.
//  Copyright (c) 2019 hb. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SignUpBusinessLogic {
    func checkUniqUser(request: CheckUniqueUSer.Request)
}

protocol SignUpDataStore {
    
}

class SignUpInteractor: SignUpBusinessLogic, SignUpDataStore {
    var presenter: SignUpPresentationLogic?
    var worker: SignUpWorker?
    
    func checkUniqUser(request: CheckUniqueUSer.Request) {
        worker = SignUpWorker()
        worker?.checkUniqueUser(request: request, completionHandler: { (response, message , success) in
            self.presenter?.presentUniqeUser(response: response, message: message ?? "", success: success ?? "0")
        })
    }
}
