//
//  ReviewAndRattingsModels.swift
//  PickUpDriver
//
//  Created by hb on 02/07/19.
//  Copyright (c) 2019 hb. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ReviewAndRattings {
    class ViewModel: WSResponseData {
        var rating: String?
        var review : String?
        var added_at : String?
        var status: String?
        var pick_up_id : String?
        var name : String?
        var profile: String?
        var id : String?
        
        private enum CodingKeys: String, CodingKey {
            case rating
            case review
            case status
            case added_at
            case pick_up_id
            case name
            case profile
            case id
        }
        
        public override func encode(to encoder: Encoder) throws {
            try super.encode(to: encoder)
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(rating, forKey: .rating)
            try container.encode(review, forKey: .review)
            try container.encode(status, forKey: .status)
            try container.encode(added_at, forKey: .added_at)
            try container.encode(pick_up_id, forKey: .pick_up_id)
            try container.encode(name, forKey: .name)
            try container.encode(profile, forKey: .profile)
            try container.encode(id, forKey: .id)
        }
        
        required public init(from decoder: Decoder) throws {
            try super.init(from: decoder)
            let values = try decoder.container(keyedBy: CodingKeys.self)
            rating = try values.decodeIfPresent(String.self, forKey: .rating)
            review = try values.decodeIfPresent(String.self, forKey: .review)
            status = try values.decodeIfPresent(String.self, forKey: .status)
            added_at = try values.decodeIfPresent(String.self, forKey: .added_at)
            pick_up_id = try values.decodeIfPresent(String.self, forKey: .pick_up_id)
            name = try values.decodeIfPresent(String.self, forKey: .name)
            profile = try values.decodeIfPresent(String.self, forKey: .profile)
            id = try values.decodeIfPresent(String.self, forKey: .id)
        }
    }
}
