//
//  ReviewAndRattingsPresenter.swift
//  PickUpDriver
//
//  Created by hb on 02/07/19.
//  Copyright (c) 2019 hb. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ReviewAndRattingsPresentationLogic {
    func presentRatings(response: [ReviewAndRattings.ViewModel]?, message: String?, success: String)
}

class ReviewAndRattingsPresenter: ReviewAndRattingsPresentationLogic {
    weak var viewController: ReviewAndRattingsDisplayLogic?
    
    func presentRatings(response: [ReviewAndRattings.ViewModel]?, message: String?, success: String) {
        self.viewController?.didReceiveRatings(response: response, message: message, success: success)
    }
}
