//
//  ReviewAndRattingsRouter.swift
//  PickUpDriver
//
//  Created by hb on 02/07/19.
//  Copyright (c) 2019 hb. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ReviewAndRattingsRoutingLogic {
    
}

protocol ReviewAndRattingsDataPassing {
    var dataStore: ReviewAndRattingsDataStore? { get set }
}

class ReviewAndRattingsRouter: NSObject, ReviewAndRattingsRoutingLogic, ReviewAndRattingsDataPassing {
    weak var viewController: ReviewAndRattingsViewController?
    var dataStore: ReviewAndRattingsDataStore?
    
}
