//
//  ReviewAndRattingsInteractor.swift
//  PickUpDriver
//
//  Created by hb on 02/07/19.
//  Copyright (c) 2019 hb. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ReviewAndRattingsBusinessLogic {
    func getRatings(indicator: Bool)
}

protocol ReviewAndRattingsDataStore {
    
}

class ReviewAndRattingsInteractor: ReviewAndRattingsBusinessLogic, ReviewAndRattingsDataStore {
    var presenter: ReviewAndRattingsPresentationLogic?
    var worker: ReviewAndRattingsWorker?
    
    func getRatings(indicator: Bool) {
        worker = ReviewAndRattingsWorker()
        worker?.ratings(indicator: indicator , completionHandler: { (respone, message, success) in
            self.presenter?.presentRatings(response: respone, message: message ?? "", success: success ?? "0")
        })
    }
}
