//
//  StaticPageModels.swift
//  Udecide
//
//  Created by hb on 15/04/19.
//  Copyright (c) 2019 hb. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum StaticPage {
    struct Request {
        var pageCode: String
    }
    
    class ViewModel: WSResponseData {
        var pageContent : String?
        var pageTitle : String?
        
        enum CodingKeys: String, CodingKey {
            case page_content
            case page_title
        }
        
        required init(from decoder: Decoder) throws {
            try super.init(from: decoder)
            let values = try decoder.container(keyedBy: CodingKeys.self)
            pageContent = try values.decodeIfPresent(String.self, forKey: .page_content)
            pageTitle = try values.decodeIfPresent(String.self, forKey: .page_title)
        }
        
        public override func encode(to encoder: Encoder) throws {
            try super.encode(to: encoder)
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(pageContent, forKey: .page_content)
            try container.encode(pageTitle, forKey: .page_title)
        }
    }
}
