//
//  GiveRatingPresenter.swift
//  PickUpUser
//
//  Created by hb on 03/07/19.
//  Copyright (c) 2019 hb. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol GiveRatingPresentationLogic {
    func presentGiveRating(message: String, success: String)
}

class GiveRatingPresenter: GiveRatingPresentationLogic {
    weak var viewController: GiveRatingDisplayLogic?
    
    func presentGiveRating(message: String, success: String) {
        self.viewController?.giveRating(message: message, success: success)
    }
}
