//
//  AddPickupRouter.swift
//  PickUpUser
//
//  Created by hb on 11/06/19.
//  Copyright (c) 2019 hb. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AddPickupRoutingLogic {
    
}

protocol AddPickupDataPassing {
    var dataStore: AddPickupDataStore? { get set }
}

class AddPickupRouter: NSObject, AddPickupRoutingLogic, AddPickupDataPassing {
    weak var viewController: AddPickupViewController?
    var dataStore: AddPickupDataStore?
    
}
