//
//  AddPickupPresenter.swift
//  PickUpUser
//
//  Created by hb on 11/06/19.
//  Copyright (c) 2019 hb. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AddPickupPresentationLogic {
    func presentAddPickUpResponse(message: String, successCode: String)
    func presentSizeResponse(response: [SizeList.ViewModel]?, message: String, successCode: String)
}

class AddPickupPresenter: AddPickupPresentationLogic {
    weak var viewController: AddPickupDisplayLogic?
    
    func presentAddPickUpResponse(message: String, successCode: String) {
         viewController?.didReceiveAddPickUpResponse(message: message, successCode: successCode)
    }
    
    func presentSizeResponse(response: [SizeList.ViewModel]?, message: String, successCode: String) {
        viewController?.didReceiveSizeResponse(response: response, message: message, successCode: successCode)
    }
}
