//
//  PastInteractor.swift
//  PickUpUser
//
//  Created by hb on 14/06/19.
//  Copyright (c) 2019 hb. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PastBusinessLogic {
    func pastRequest(request: Deliveries.Request, showLoader: Bool)
}

protocol PastDataStore {
    //var name: String { get set }
}

class PastInteractor: PastBusinessLogic, PastDataStore {
    var presenter: PastPresentationLogic?
    var worker: PastWorker?
    
    func pastRequest(request: Deliveries.Request, showLoader: Bool) {
        worker = PastWorker()
        worker?.PickUpList(request: request, showLoader: showLoader, completionHandler: { (response, message, success) in
            self.presenter?.presentPastDeliveries(response: response, message: message ?? "", success: success ?? "0")
        })
    }
}
