//
//  PastPresenter.swift
//  PickUpUser
//
//  Created by hb on 14/06/19.
//  Copyright (c) 2019 hb. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PastPresentationLogic {
    func presentPastDeliveries(response: [Deliveries.ViewModel]?, message: String, success: String)
}

class PastPresenter: PastPresentationLogic {
    weak var viewController: PastDisplayLogic?
    
    func presentPastDeliveries(response: [Deliveries.ViewModel]?, message: String, success: String) {
        self.viewController?.didReceivePastDeliveries(response: response, message: message, success: success)
    }
}
