//
//  DetailsPresenter.swift
//  PickUpUser
//
//  Created by hb on 17/06/19.
//  Copyright (c) 2019 hb. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DetailsPresentationLogic {
    func presentDetails(response: PickUpDetail.ViewModel?, message: String, success: String) 
}

class DetailsPresenter: DetailsPresentationLogic {
    weak var viewController: DetailsDisplayLogic?
    
    func presentDetails(response: PickUpDetail.ViewModel?, message: String, success: String) {
        self.viewController?.didReceiveDetails(response: response, message: message, success: success)
    }
}
