//
//  PendingInteractor.swift
//  PickUpUser
//
//  Created by hb on 14/06/19.
//  Copyright (c) 2019 hb. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PendingBusinessLogic {
    func pendingRequest(request: Deliveries.Request, showLoader: Bool)
}

protocol PendingDataStore {
    
}

class PendingInteractor: PendingBusinessLogic, PendingDataStore {
    var presenter: PendingPresentationLogic?
    var worker: PendingWorker?
    
    func pendingRequest(request: Deliveries.Request, showLoader: Bool) {
        worker = PendingWorker()
        worker?.PickUpList(request: request, showLoader: showLoader, completionHandler: { (response, message, success) in
            self.presenter?.presentPendingDeliveries(response: response, message: message ?? "", success: success ?? "0")
        })
    }
}
