//
//  PaymentCardListingPresenter.swift
//  ForgetMeKnots
//
//  Created by hb on 23/05/19.
//  Copyright (c) 2019 hb. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PaymentCardListingPresentationLogic {
    func presentCardList(response: [PaymentCardListing.ViewModel]?, message: String, success:String)
    func presentRemoveCard(message: String, success:String)
    func presentAcceptRejectOffer(message: String, success: String)
    func presentAddTip(message: String, success: String)
}

class PaymentCardListingPresenter: PaymentCardListingPresentationLogic {
    weak var viewController: PaymentCardListingDisplayLogic?
    
    
    func presentCardList(response: [PaymentCardListing.ViewModel]?, message: String, success:String) {
        self.viewController?.didReceiveCardList(response: response, message: message, success: success)
    }
    
    func presentRemoveCard(message: String, success:String) {
        self.viewController?.didReceiveRemoveCard(message: message, success: success)
    }
    
    func presentAcceptRejectOffer(message: String, success: String) {
        self.viewController?.didReceiveAcceptRejectOffer(message: message, success: success)
    }
    
    func presentAddTip(message: String, success: String) {
        self.viewController?.didReceiveAddTip(message: message, success: success)
    }
}
