//
//  VerifyOtpRouter.swift
//  PickUpUser
//
//  Created by hb on 07/06/19.
//  Copyright (c) 2019 hb. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol VerifyOtpRoutingLogic {
    func redirectToHome(response: Login.Authentication.ViewModel)
}

protocol VerifyOtpDataPassing {
    var dataStore: VerifyOtpDataStore? { get }
}

class VerifyOtpRouter: NSObject, VerifyOtpRoutingLogic, VerifyOtpDataPassing {
    weak var viewController: VerifyOtpViewController?
    var dataStore: VerifyOtpDataStore?
    
    func redirectToHome(response: Login.Authentication.ViewModel) {
        TruckItSessionHandler.shared.setLoggedUserDetails(userDetail: response)
        if let homeVc = HomeViewController.instance() {
            let vc = NavController.init(rootViewController: homeVc)
            AppConstants.appDelegate.window?.rootViewController = vc
        }
    }
}
