//
//  VerifyOtpPresenter.swift
//  PickUpUser
//
//  Created by hb on 07/06/19.
//  Copyright (c) 2019 hb. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol VerifyOtpPresentationLogic {
    func presentSignUp(response: Login.Authentication.ViewModel?, message: String, success: String)
    func presentChangePhoneResponse(message: String, success: String)
}

class VerifyOtpPresenter: VerifyOtpPresentationLogic {
    weak var viewController: VerifyOtpDisplayLogic?
    
    func presentSignUp(response: Login.Authentication.ViewModel?, message: String, success: String) {
        self.viewController?.didReceiveSignUpResponse(response: response, message: message, success: success)
    }
    
    func presentChangePhoneResponse(message: String, success: String) {
        self.viewController?.didReceiveChangePhoneResponse(message: message, success: success)
    }
    
}
