//
//  VerifyOtpInteractor.swift
//  PickUpUser
//
//  Created by hb on 07/06/19.
//  Copyright (c) 2019 hb. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol VerifyOtpBusinessLogic {
    func signUp(request: SignUp.Request)
    func changePhone(request: VerifyOtp.Request)
}

protocol VerifyOtpDataStore {
}

class VerifyOtpInteractor: VerifyOtpBusinessLogic, VerifyOtpDataStore {
    var presenter: VerifyOtpPresentationLogic?
    var worker: VerifyOtpWorker?
    
    func signUp(request: SignUp.Request) {
        worker = VerifyOtpWorker()
        worker?.signUp(request: request, completionHandler: { (response, message, success) in
            self.presenter?.presentSignUp(response: response, message: message ?? "", success: success ?? "0")
        })
    }
    
    func changePhone(request: VerifyOtp.Request) {
        worker = VerifyOtpWorker()
        worker?.changePhone(request: request, completionHandler: { (message, success) in
            self.presenter?.presentChangePhoneResponse(message: message ?? "", success: success ?? "0")
        })
    }
}
