//
//  AddPaymentCardRouter.swift
//  ForgetMeKnots
//
//  Created by hb on 23/05/19.
//  Copyright (c) 2019 hb. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AddPaymentCardRoutingLogic {
    
}

protocol AddPaymentCardDataPassing {
    var dataStore: AddPaymentCardDataStore? { get set }
}

class AddPaymentCardRouter: NSObject, AddPaymentCardRoutingLogic, AddPaymentCardDataPassing {
    weak var viewController: AddPaymentCardViewController?
    var dataStore: AddPaymentCardDataStore?
}
