//
//  AddPaymentCardInteractor.swift
//  ForgetMeKnots
//
//  Created by hb on 23/05/19.
//  Copyright (c) 2019 hb. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AddPaymentCardBusinessLogic {
    func saveCard(request: AddPaymentCard.Request)
}

protocol AddPaymentCardDataStore {
    
}

class AddPaymentCardInteractor: AddPaymentCardBusinessLogic, AddPaymentCardDataStore {
    
    var presenter: AddPaymentCardPresentationLogic?
    var worker: AddPaymentCardWorker?
    
    func saveCard(request: AddPaymentCard.Request) {
        worker = AddPaymentCardWorker()
        worker?.addCard(request: request, completionHandler: { (response, message, success) in
            self.presenter?.presentSaveCard(response: response, message: message ?? "", success: success ?? "0")
        })
    }
}
