//
//  AddPaymentCardModels.swift
//  ForgetMeKnots
//
//  Created by hb on 23/05/19.
//  Copyright (c) 2019 hb. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum AddPaymentCard {
    struct Request {
        var stripeToken: String
    }
    
    
    class ViewModel: WSResponseData {
        var stripe_card_id : String?
        
        enum CodingKeys: String, CodingKey {
            case stripe_card_id
        }
        
        required init(from decoder: Decoder) throws {
            try super.init(from: decoder)
            let values = try decoder.container(keyedBy: CodingKeys.self)
            stripe_card_id = try values.decodeIfPresent(String.self, forKey: .stripe_card_id)
        }
        
        public override func encode(to encoder: Encoder) throws {
            try super.encode(to: encoder)
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(stripe_card_id, forKey: .stripe_card_id)
        }
    }
}
