//
//  RatingPresenter.swift
//  TruckIt
//
//  Created by hb on 28/05/20.
//  Copyright (c) 2020 hb. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol RatingPresentationLogic
{
    func presentGiveRating(message: String, success: String)
    func presentDontShowPop(message: String, success: String)
    
}

class RatingPresenter: RatingPresentationLogic
{
    weak var viewController: RatingDisplayLogic?
    
    func presentGiveRating(message: String, success: String) {
        self.viewController?.giveRating(message: message, success: success)
    }
    func presentDontShowPop(message: String, success: String)
    {
        self.viewController?.dontShowPopUp(message: message, success: success)
    }
}
