
//
//  RatingInteractor.swift
//  TruckIt
//
//  Created by hb on 28/05/20.
//  Copyright (c) 2020 hb. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol RatingBusinessLogic
{
    func giveRating(req: GiveRating.Request)
    func dontShowPopUp(req: DontShowPopUp.Request)

}

protocol RatingDataStore
{
  //var name: String { get set }
}

class RatingInteractor: RatingBusinessLogic, RatingDataStore
{
  var presenter: RatingPresentationLogic?
  var worker: RatingWorker?
  //var name: String = ""
  
  // MARK: Do something
  
 func giveRating(req: GiveRating.Request) {
        worker = RatingWorker()
        worker?.giveRating(request: req, completionHandler: { (message, success) in
            self.presenter?.presentGiveRating(message: message ?? "", success: success ?? "0")
        })
    }
    
    func dontShowPopUp(req: DontShowPopUp.Request)
    {
        worker = RatingWorker()
        worker?.dontShowRatingPopUp(request: req, completionHandler: { (message, success) in
            self.presenter?.presentDontShowPop(message: message ?? "", success: success ?? "")
        })
           
    }
}
