//
//  EditProfileInteractor.swift
//  Udecide
//
//  Created by hb on 15/04/19.
//  Copyright (c) 2019 hb. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol EditProfileBusinessLogic {
    func editProfile(request: EditProfile.Request)
}

protocol EditProfileDataStore {
    
}

class EditProfileInteractor: EditProfileBusinessLogic, EditProfileDataStore {
    var presenter: EditProfilePresentationLogic?
    var worker: EditProfileWorker?
    
    func editProfile(request: EditProfile.Request) {
        worker = EditProfileWorker()
        worker?.editProfile(request: request, completionHandler: { (response, message, success) in
            self.presenter?.presentEditProfile(response: response, message: message ?? "", success: success ?? "0")
        })
    }
    
}
