//
//  ForgotPasswordRouter.swift
//  Udecide
//
//  Created by hb on 11/04/19.
//  Copyright (c) 2019 hb. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ForgotPasswordRoutingLogic {
    
}

protocol ForgotPasswordDataPassing {
    var dataStore: ForgotPasswordDataStore? { get set }
}

class ForgotPasswordRouter: NSObject, ForgotPasswordRoutingLogic, ForgotPasswordDataPassing {
    weak var viewController: ForgotPasswordViewController?
    var dataStore: ForgotPasswordDataStore?
    
}
