//
//  ForgotPasswordInteractor.swift
//  Udecide
//
//  Created by hb on 11/04/19.
//  Copyright (c) 2019 hb. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ForgotPasswordBusinessLogic {
    func forgotPassword(request: ForgotPassword.Request)
}

protocol ForgotPasswordDataStore {
    
}

class ForgotPasswordInteractor: ForgotPasswordBusinessLogic, ForgotPasswordDataStore {
    
    var presenter: ForgotPasswordPresentationLogic?
    var worker: ForgotPasswordWorker?
    
    func forgotPassword(request: ForgotPassword.Request) {
        worker = ForgotPasswordWorker()
        worker?.forgotPassword(request: request, completionHandler: { (response, message, success) in
            self.presenter?.presentForgotPassword(response: response, message: message ?? "", success: success ?? "0")
        })
    }
    
}
