//
//  AcceptRejectOfferInteractor.swift
//  PickUpUser
//
//  Created by hb on 19/06/19.
//  Copyright (c) 2019 hb. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AcceptRejectOfferBusinessLogic {
    func acceptRejectOrder(request: AcceptRejectOffer.Request)
}

protocol AcceptRejectOfferDataStore {
    
}

class AcceptRejectOfferInteractor: AcceptRejectOfferBusinessLogic, AcceptRejectOfferDataStore {
    var presenter: AcceptRejectOfferPresentationLogic?
    var worker: AcceptRejectOfferWorker?
    
    func acceptRejectOrder(request: AcceptRejectOffer.Request) {
        worker = AcceptRejectOfferWorker()
        worker?.acceptRejectOfffer(request: request, completionHandler: { (message, success) in
            self.presenter?.presentAcceptRejectOffer(message: message ?? "", success: success ?? "0")
        })
    }
}
