//
//  LoginInteractor.swift
//  Udecide
//
//  Created by hb on 09/04/19.
//  Copyright (c) 2019 hb. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginBusinessLogic {
    func login(request: Login.Authentication.Request)
}

protocol LoginDataStore {
    
}

class LoginInteractor: LoginBusinessLogic, LoginDataStore {
    var presenter: LoginPresentationLogic?
    var worker: LoginWorker?
    
    func login(request: Login.Authentication.Request) {
        worker = LoginWorker()
        worker?.login(request: request, completionHandler: { (response, message, success) in
            self.presenter?.presentLogin(response: response, message: message ?? "", success: success ?? "0")
        })
    }
}
