//
//  LoginRouter.swift
//  Udecide
//
//  Created by hb on 09/04/19.
//  Copyright (c) 2019 hb. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginRoutingLogic {
    func redirectToHome(response: Login.Authentication.ViewModel)
    func redirectToForgotPassword()
    func redirectToSignUp()
}

protocol LoginDataPassing {
    var dataStore: LoginDataStore? { get set }
}

class LoginRouter: NSObject, LoginRoutingLogic, LoginDataPassing {
    weak var viewController: LoginViewController?
    var dataStore: LoginDataStore?
    
    func redirectToHome(response: Login.Authentication.ViewModel) {
        TruckItSessionHandler.shared.setLoggedUserDetails(userDetail: response)
        if let homeVc = HomeViewController.instance() {
            let vc = NavController.init(rootViewController: homeVc)
            AppConstants.appDelegate.window?.rootViewController = vc
        }
    }
    
    func redirectToForgotPassword() {
        if let forgotPasswordVc = ForgotPasswordViewController.instance() {
            self.viewController?.navigationController?.pushViewController(forgotPasswordVc, animated: true)
        }
    }
    
    func redirectToSignUp() {
        if let signUpVc = SignUpViewController.instance() {
            self.viewController?.navigationController?.pushViewController(signUpVc, animated: true)
        }
    }
}
