//
//  ResetPasswordPresenter.swift
//  PickUpUser
//
//  Created by hb on 10/06/19.
//  Copyright (c) 2019 hb. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ResetPasswordPresentationLogic {
  func presentResetPassword(message: String, success: String)
}

class ResetPasswordPresenter: ResetPasswordPresentationLogic {
    
    
  weak var viewController: ResetPasswordDisplayLogic?
  
    func presentResetPassword(message: String, success: String) {
        viewController?.didReceivecResetPasswordResponse(message: message, success: success)
    }
  
}
