//
//  ResetPasswordInteractor.swift
//  PickUpUser
//
//  Created by hb on 10/06/19.
//  Copyright (c) 2019 hb. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ResetPasswordBusinessLogic {
    func resetPasswordPassword(request: ResetPassword.Request)
}

protocol ResetPasswordDataStore {
    
}

class ResetPasswordInteractor: ResetPasswordBusinessLogic, ResetPasswordDataStore {
    
    var presenter: ResetPasswordPresentationLogic?
    var worker: ResetPasswordWorker?
    
    func resetPasswordPassword(request: ResetPassword.Request) {
        worker = ResetPasswordWorker()
        worker?.resetPassword(request: request, completionHandler: { (message, success) in
            self.presenter?.presentResetPassword(message: message ?? "", success: success ?? "0")
        })
    }
    
}
