//
//  OffersPresenter.swift
//  PickUpUser
//
//  Created by hb on 18/06/19.
//  Copyright (c) 2019 hb. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol OffersPresentationLogic {
    func presentOffers(response: [Offers.ViewModel]?, message: String, success: String)
}

class OffersPresenter: OffersPresentationLogic {
    weak var viewController: OffersDisplayLogic?
    
    func presentOffers(response: [Offers.ViewModel]?, message: String, success: String)  {
        self.viewController?.didReceiveOffers(response: response, message: message, success: success)
    }
}
