//
//  OffersInteractor.swift
//  PickUpUser
//
//  Created by hb on 18/06/19.
//  Copyright (c) 2019 hb. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol OffersBusinessLogic {
    func offers(request: Offers.Request, showLoader: Bool)
}

protocol OffersDataStore {
    
}

class OffersInteractor: OffersBusinessLogic, OffersDataStore {
    var presenter: OffersPresentationLogic?
    var worker: OffersWorker?
    
    func offers(request: Offers.Request, showLoader: Bool) {
        worker = OffersWorker()
        worker?.offers(request: request, showLoader: showLoader, completionHandler: { (response, message, success) in
            self.presenter?.presentOffers(response: response, message: message ?? "", success: success ?? "0")
        })
    }
}
