//
//  ChangePasswordPresenter.swift
//  Udecide
//
//  Created by hb on 15/04/19.
//  Copyright (c) 2019 hb. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ChangePasswordPresentationLogic {
    func presentChangePassword(message: String, success: String)
}

class ChangePasswordPresenter: ChangePasswordPresentationLogic {
    weak var viewController: ChangePasswordDisplayLogic?
    
    func presentChangePassword(message: String, success: String) {
        self.viewController?.didReceivecChangePasswordResponse(message: message, success: success)
    }
}
