//
//  PastPickUpDetailRouter.swift
//  PickUpDriver
//
//  Created by hb on 11/07/19.
//  Copyright (c) 2019 hb. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PastPickUpDetailRoutingLogic {
    
}

protocol PastPickUpDetailDataPassing {
    var dataStore: PastPickUpDetailDataStore? { get set }
}

class PastPickUpDetailRouter: NSObject, PastPickUpDetailRoutingLogic, PastPickUpDetailDataPassing {
    weak var viewController: PastPickUpDetailViewController?
    var dataStore: PastPickUpDetailDataStore?
    
}
