//
//  PastPickUpDetailInteractor.swift
//  PickUpDriver
//
//  Created by hb on 11/07/19.
//  Copyright (c) 2019 hb. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PastPickUpDetailBusinessLogic {
    func pickUpDetail(request: PickUpDetail.Request)
}

protocol PastPickUpDetailDataStore {
    
}

class PastPickUpDetailInteractor: PastPickUpDetailBusinessLogic, PastPickUpDetailDataStore {
    var presenter: PastPickUpDetailPresentationLogic?
    var worker: PastPickUpDetailWorker?
    
    
    func pickUpDetail(request: PickUpDetail.Request) {
        worker = PastPickUpDetailWorker()
        worker?.details(request: request, completionHandler: { (response, message, success) in
            self.presenter?.presentDetails(response: response, message: message ?? "", success: success ?? "")
        })
    }
}
