//
//  DriverProfileRouter.swift
//  PickUpUser
//
//  Created by hb on 20/06/19.
//  Copyright (c) 2019 hb. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DriverProfileRoutingLogic {
    
}

protocol DriverProfileDataPassing {
    var dataStore: DriverProfileDataStore? { get set}
}

class DriverProfileRouter: NSObject, DriverProfileRoutingLogic, DriverProfileDataPassing {
    weak var viewController: DriverProfileViewController?
    var dataStore: DriverProfileDataStore?
}
