//
//  ReportAProblemInteractor.swift
//  Udecide
//
//  Created by hb on 17/04/19.
//  Copyright (c) 2019 hb. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ReportAProblemBusinessLogic {
    func reportAProblem(request: ReportAProblem.Request)
}

protocol ReportAProblemDataStore {
    
}

class ReportAProblemInteractor: ReportAProblemBusinessLogic, ReportAProblemDataStore {
    var presenter: ReportAProblemPresentationLogic?
    var worker: ReportAProblemWorker?
    
    func reportAProblem(request: ReportAProblem.Request) {
        worker = ReportAProblemWorker()
        worker?.reportAProblem(request: request, completionHandler: { (message, success) in
            self.presenter?.presentReport(message: message ?? "", success: success ?? "0")
        })
        
    }
}
