//
//  ReportAProblemPresenter.swift
//  Udecide
//
//  Created by hb on 17/04/19.
//  Copyright (c) 2019 hb. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ReportAProblemPresentationLogic {
    func presentReport(message: String, success: String)
}

class ReportAProblemPresenter: ReportAProblemPresentationLogic {
    weak var viewController: ReportAProblemDisplayLogic?
    
    func presentReport(message: String, success: String) {
        self.viewController?.didReceiveResponse(message: message, success: success)
    }
}
