//
//  SettingsPresenter.swift
//  Udecide
//
//  Created by hb on 15/04/19.
//  Copyright (c) 2019 hb. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SettingsPresentationLogic {
    func presentLogout(message: String, success: String)
    func presentDeleteAccount(message: String, success: String)
}

class SettingsPresenter: SettingsPresentationLogic {
    weak var viewController: SettingsDisplayLogic?
    
    func presentLogout(message: String, success: String) {
        self.viewController?.didReceiveLogoutResponse(message: message, success: success)
    }
    
    func presentDeleteAccount(message: String, success: String) {
        self.viewController?.didReceiveDeleteAccountResponse(message: message, success: success)
    }
}
