//
//  TipWorker.swift
//  TruckIt
//
//  Created by hb on 30/12/19.
//  Copyright (c) 2019 hb. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class TipWorker {

}
