//
//  CancelPickupRouter.swift
//  PickUpUser
//
//  Created by hb on 23/07/19.
//  Copyright (c) 2019 hb. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CancelPickupRoutingLogic {
    
}

protocol CancelPickupDataPassing {
    var dataStore: CancelPickupDataStore? { get set }
}

class CancelPickupRouter: NSObject, CancelPickupRoutingLogic, CancelPickupDataPassing {
    weak var viewController: CancelPickupViewController?
    var dataStore: CancelPickupDataStore?
    
}
