//
//  CancelPickupInteractor.swift
//  PickUpUser
//
//  Created by hb on 23/07/19.
//  Copyright (c) 2019 hb. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CancelPickupBusinessLogic {
    func cancelPickup(request: CancelPickup.Request)
}

protocol CancelPickupDataStore {
    
}

class CancelPickupInteractor: CancelPickupBusinessLogic, CancelPickupDataStore {
    var presenter: CancelPickupPresentationLogic?
    var worker: CancelPickupWorker?
    
    func cancelPickup(request: CancelPickup.Request) {
        worker = CancelPickupWorker()
        worker?.cancelPickup(request: request, completionHandler: { (message, success) in
            self.presenter?.presentCancelPickup(message: message ?? "", success: success ?? "0")
        })
    }
}
