//
//  CancelPickupPresenter.swift
//  PickUpUser
//
//  Created by hb on 23/07/19.
//  Copyright (c) 2019 hb. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CancelPickupPresentationLogic {
    func presentCancelPickup(message: String, success: String)
}

class CancelPickupPresenter: CancelPickupPresentationLogic {
    weak var viewController: CancelPickupDisplayLogic?
    
    func presentCancelPickup(message: String, success: String) {
        self.viewController?.didReceiveCancelPickup(message: message, success: success)
    }
}
