//
//  HomePresenter.swift
//  Udecide
//
//  Created by hb on 11/04/19.
//  Copyright (c) 2019 hb. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomePresentationLogic {
    func presentNearPickUpList(response: [Home.ViewModel]?, message: String, successCode: String)
    func getConfig(response: BackGroundCheck.ViewModel?, message: String, succes: String)
    func addRating(response: PickUpDetail.ViewModel?, message: String, success: String)
    func presentEditProfile(response: Login.Authentication.ViewModel?, message: String, success: String)

}

class HomePresenter: HomePresentationLogic {
    
    weak var viewController: HomeDisplayLogic?
    
    func presentNearPickUpList(response: [Home.ViewModel]?, message: String, successCode: String) {
        viewController?.didReceiveNearPickUpListResponse(viewmodel: response, message: message, successCode: successCode)
    }
    
    func getConfig(response: BackGroundCheck.ViewModel?, message: String, succes: String) {
        self.viewController?.getConfig(response: response, message: message, succes: succes)
    }
    
    func addRating(response: PickUpDetail.ViewModel?, message: String, success: String) {
           self.viewController?.addRating(response: response, message: message, success: success)
       }

    func presentEditProfile(response: Login.Authentication.ViewModel?, message: String, success: String) {
        self.viewController?.didReceiveEditProfileResponse(response: response, message: message, success: success)
    }
}
