//
//  MessagePresenter.swift
//  PickUpDriver
//
//  Created by hb on 17/07/19.
//  Copyright (c) 2019 hb. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MessagePresentationLogic {
    func presentReadUnreadMessage(message: String, success: String)
    func presentSendMessage(message: String, success: String)
    func didReceivePickupStatus(response: PickupStatus.ViewModel?, message: String, success: String)
}

class MessagePresenter: MessagePresentationLogic {
    weak var viewController: MessageDisplayLogic?
    
    func presentReadUnreadMessage(message: String, success: String) {
        self.viewController?.didReceiveReadUnreadMessage(message: message, success: success)
    }
    
    func presentSendMessage(message: String, success: String) {
        self.viewController?.didReceiveSendMessage(message: message, success: success)
    }
    
    func didReceivePickupStatus(response: PickupStatus.ViewModel?, message: String, success: String) {
        self.viewController?.didReceivePickupStatus(response: response, message: message, success: success)
    }
}
