//
//  OngoingRouter.swift
//  PickUpUser
//
//  Created by hb on 14/06/19.
//  Copyright (c) 2019 hb. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol OngoingRoutingLogic {
    
}

protocol OngoingDataPassing {
    var dataStore: OngoingDataStore? { get set }
}

class OngoingRouter: NSObject, OngoingRoutingLogic, OngoingDataPassing {
    weak var viewController: OngoingViewController?
    var dataStore: OngoingDataStore?
    
}
