//
//  ReportUserWorker.swift
//  PickUpUser
//
//  Created by hb on 03/07/19.
//  Copyright (c) 2019 hb. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class ReportUserWorker {
    func reportUser(request: ReportUser.Request,completionHandler: @escaping (_ message: String?, _ successCode: String?) -> Void) {
        NetworkService.dataRequest(with: DriverAPIRouter.reportUser(request: request), showLoader: true) { (responce: WSResponse<ReportUser.ViewModel>?, error: NetworkError?) in
            if let detail = responce {
                if let resparray = detail.arrayData,resparray.count > 0, let success = detail.setting?.isSuccess, let msg = detail.setting?.message, success {
                    completionHandler( msg, detail.setting?.success)
                } else {
                    completionHandler( detail.setting?.message, detail.setting?.success)
                }
            } else {
                completionHandler(error?.errorMessage() ?? AlertMessage.defaultError, "0")
            }
        }
    }
    
    func reportReason(completionHandler: @escaping ([ReportReason.ViewModel]?, _ message: String?, _ successCode: String?) -> Void) {
        NetworkService.dataRequest(with: DriverAPIRouter.reasonList, showLoader: true) { (responce: WSResponse<ReportReason.ViewModel>?, error: NetworkError?) in
            if let detail = responce {
                if let resparray = detail.arrayData,resparray.count > 0, let success = detail.setting?.isSuccess, let msg = detail.setting?.message, success {
                    completionHandler( resparray, msg, detail.setting?.success)
                } else {
                    completionHandler(nil, detail.setting?.message, detail.setting?.success)
                }
            } else {
                completionHandler(nil, error?.errorMessage() ?? AlertMessage.defaultError, "0")
            }
        }
    }
}
