//
//  ProcessRouter.swift
//  PickUpUser
//
//  Created by hb on 18/06/19.
//  Copyright (c) 2019 hb. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ProcessRoutingLogic {
    
}

protocol ProcessDataPassing {
    var dataStore: ProcessDataStore? { get set }
}

class ProcessRouter: NSObject, ProcessRoutingLogic, ProcessDataPassing {
    weak var viewController: ProcessViewController?
    var dataStore: ProcessDataStore?
    
}
